name: CI - Build and Deploy Allure Report

on:
  schedule:
    - cron: '0 14 * * 2,4'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      allure:
        description: 'Generate Allure Report?'
        required: false
        default: 'true'
        type: choice
        options:
          - true
          - false
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and run tests
        run: |
          mvn clean test
        continue-on-error: true

      - name: Install Allure Commandline
        run: |
          curl -o allure.zip -L https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.tgz
          tar -zxvf allure.zip
          sudo mv allure-2.17.2 /usr/local/bin/allure
        continue-on-error: true


      - name: Generate Allure Report
        if: ${{ env.allure == 'true' }}
        run: |
          allure generate allure-results --clean -o allure-report
          mv -f allure-report/history allure-results/history
          allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Deploy Allure Report to GitHub Pages
        if: ${{ env.allure == 'true' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          continue-on-error: true