name: CI - Build and Deploy Allure Report

on:
  schedule:
    - cron: '0 14 * * 2,4'
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and run tests
        run: |
          mvn clean test
        continue-on-error: true

      - name: Install Allure Commandline
        run: |
          curl -o allure-commandline.zip -L "https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.9/allure-commandline-2.13.9.zip"
          unzip -o allure-commandline.zip -d allure
          export PATH=$PATH:$PWD/allure/allure-2.13.9/bin
        continue-on-error: true

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
          mv -f allure-report/history allure-results/history
          allure generate allure-results --clean -o allure-report
        continue-on-error: true

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
        continue-on-error: true